[package]
name = "task03"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.2"
rand = "0.9.0"
anyhow = "1.0.97"
clap = { version = "4.5.34", features = ["derive"] }
del-canvas = "0.1.5"