[package]
name = "task05"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
del-canvas = "=0.1.7"
nalgebra = "0.33.2"
rand = "0.9.0"
rand_chacha = "0.9.0"
slice-of-array = "0.3.2"
clap = { version = "=4.5.38", features = ["derive"] }